pipeline {
    agent any

    environment {
        PROJECT_ID = 'yt-comments-478714'
    }

    stages {
        stage('Checkout SCM') {
            steps {
                checkout scm
            }
        }

        stage('Run Sentiment Analysis') {
    steps {
        withCredentials([file(credentialsId: 'gcp-sa-key', variable: 'SERVICE_ACCOUNT_KEY')]) { 
            withEnv(["GOOGLE_APPLICATION_CREDENTIALS=${SERVICE_ACCOUNT_KEY}"]) {
                dir('yt-comments-gcp') {   // 👈 IMPORTANT
                    sh '''
                    echo "Activating service account..."
                    gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
                    
                    echo "Setting GCP project..."
                    gcloud config set project $PROJECT_ID

                    echo "Verifying credentials..."
                    gcloud auth list

                    echo "Running Ansible playbook..."
                    ansible-playbook -i ansible/inventory ansible/playbooks/run_pretrained_sentiment.yml
                    '''
                }
            }
        }
    }
}

} 